site_name: My Documentation
site_url: https://your-username.github.io/your-repo-name/
nav:
  - "ראשי": index.md
  - "מדריך ממשק": מדריך-ממשק.md
  - "מצב אונליין": מצב-אונליין.md
  - "מצב הורדה": מצב-הורדה.md
  - "תצוגת תמונה ( )": תצוגת-תמונה.md
  - "אייקון תצוגה ( )": אייקון-תצוגה.md
  - "מחרוזת תצוגה ( )": מחרוזת-תצוגה.md
  - "מחרוזת תצוגת גלילה ( )": מחרוזת-תצוגת-גלילה.md
  - "הגדר פיקסל x( ) y( ) בהירות ( )": הגדר-פיקסל-x-y-בהירות.md
  - "ניקוי תצוגהמנקה את תוכן התצוגה במטריצת הנקודות. דוגמה:": ניקוי-תצוגהמנקה-את-תוכן-התצוגה-במטריצת-הנקודות-דוגמה.md
  - "כאשר לחצן ( ) נלחץ": כאשר-לחצן-נלחץ.md
  - "ערך בהירות": ערך-בהירות.md
  - "טמפרטורה": טמפרטורה.md
  - "סאונד": סאונד.md
  - "כיול המצפן": כיול-המצפן.md
  - "כיוון מצפן": כיוון-מצפן.md
  - "עוצמה מגנטית": עוצמה-מגנטית.md
  - "( ) מחווה": מחווה.md
  - "האצה ( )": האצה.md
  - "נגן מוזיקה ( )": נגן-מוזיקה.md
  - "הגדרת מהירות השמעה ( )": הגדרת-מהירות-השמעה.md
  - "תדר טון ( ) נגינה רציפה": תדר-טון-נגינה-רציפה.md
  - "הפסקת ניגון רציף": הפסקת-ניגון-רציף.md
  - "נגן סאונד אקספרסיבי ( )": נגן-סאונד-אקספרסיבי.md
  - "הגדרת עוצמת הקול": הגדרת-עוצמת-הקול.md
  - "הדובר": הדובר.md
  - "חיישן פוטואלקטרי לטווח ארוך ( )": חיישן-פוטואלקטרי-לטווח-ארוך.md
  - "פוטנציומטר ( )": פוטנציומטר.md
  - "חיישן רמת אפור": חיישן-רמת-אפור.md
  - "חיישן רגיש לאור ( )": חיישן-רגיש-לאור.md
  - "חיישן להבה ( )": חיישן-להבה.md
  - "חיישן מפלס המים( )": חיישן-מפלס-המים.md
  - "חיישן גז MQ-2": חיישן-גז-mq-2.md
  - "חיישן לחות קרקע ( )": חיישן-לחות-קרקע.md
  - "חיישן טמפרטורה ( )": חיישן-טמפרטורה.md
  - "חיישן הול ( )": חיישן-הול.md
  - "חיישן לחצן ( )": חיישן-לחצן.md
  - "חיישן אולטרסוני (P13, P0) יחידת סנטימטר": חיישן-אולטרסוני-p13-p0-יחידת-סנטימטר.md
  - "דיסקט רוקר": דיסקט-רוקר.md
  - "רוקר ( ) כיוון": רוקר-כיוון.md
  - "Action Servo ( ) זווית ( )": action-servo-זווית.md
  - "מנוע ( ) זווית ( )": מנוע-זווית.md
  - "מאוורר ( ) מעבר ל ( )": מאוורר-מעבר-ל.md
  - "אלקטרומגנט ( ) מעבר ל ( )": אלקטרומגנט-מעבר-ל.md
  - "קרא מיקום מנוע": קרא-מיקום-מנוע.md
  - "מנוע שמאל מוגדר ל- ( ) מנוע ימין מוגדר ל- ( )": מנוע-שמאל-מוגדר-ל-מנוע-ימין-מוגדר-ל.md
  - "מנועים כפולים ב-( ) ( ) מהירות סיבוב ( ) שניות": מנועים-כפולים-ב-מהירות-סיבוב-שניות.md
  - "מנועים כפולים ב-( ) ( ) מהירות סיבוב ( ) מעלות": מנועים-כפולים-ב-מהירות-סיבוב-מעלות.md
  - "מנועים כפולים במהירות () ( ) סיבוב מהיר": מנועים-כפולים-במהירות-סיבוב-מהיר.md
  - "המנוע במהירות ( ) סיבוב ( ) מעלות": המנוע-במהירות-סיבוב-מעלות.md
  - "( ) מנוע ב ( ) מהירות סיבוב ( ) שניות": מנוע-ב-מהירות-סיבוב-שניות.md
  - "( ) המנוע במהירות ( ) הלך למיקום ( )": המנוע-במהירות-הלך-למיקום.md
  - "( ) מנוע במהירות ( ) סיבוב מהיר": מנוע-במהירות-סיבוב-מהיר.md
  - "מתג LED ל-( )": מתג-led-ל.md
  - "טבעת אור ( ) הגדרת בהירות ( )": טבעת-אור-הגדרת-בהירות.md
  - "טבעת אור ( ) צבע תצוגה ( )": טבעת-אור-צבע-תצוגה.md
  - "אתחול OLED": אתחול-oled.md
  - "טקסט תצוגה ( ) ב-X ( ) Y ( ) עם מצב צבע ( )": טקסט-תצוגה-ב-x-y-עם-מצב-צבע.md
  - "לייזר ( ) מעבר ל- ( )": לייזר-מעבר-ל.md
  - "מודול הקלטה - נגינה": מודול-הקלטה-נגינה.md
  - "מצב מקוון (מצב אינטראקטיבי": מצב-מקוון-מצב-אינטראקטיבי.md
  - "מצב הורדה": מצב-הורדה.md
theme:
  name: material
  language: he
  font:
    text: Heebo
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
