site_name: My Documentation
site_url: https://your-username.github.io/your-repo-name/
nav:
  - "ראשי": index.md
  - "מדריך ממשק": מדריך-ממשק.md
  - "**( ) המנוע במהירות ( ) הלך למיקום ( )**": המנוע-במהירות-הלך-למיקום.md
  - "**( ) מנוע במהירות ( ) סיבוב מהיר**": מנוע-במהירות-סיבוב-מהיר.md
theme:
  name: material
  language: he
  font:
    text: Alef
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
